---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    demo: nginx
spec:
  selector:
    matchLabels:
      demo: nginx
  replicas: 3
  template:
    metadata:
      labels:
        demo: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    demo: nginx
spec:
  ports:
  - port: 80
  selector:
    demo: nginx